uktrade/market-access-api

config/settings.py

HawkRequest package doesn't allow name and id to be different in credentials. Fixed it by using the same env var.

Fix for HawkRequest package

---

requirements.txt

in latest commit that hasn't been released yet. We need it for latest Django. So adding commit instead

HawkRest has a fix

---

api/barriers/models.py
api/barriers/serializers.py
api/barriers/tests/test_barrier_details.py
api/barriers/tests/test_list_barriers.py
api/barriers/views.py
api/core/models.py
api/metadata/constants.py
api/metadata/views.py
config/urls.py

Merging status history feature into master, for production deployment.
Status history will allow front end to show who started the report, who submitted it and who resolved it. As well as any other status changes that were made during a barrier's life time.

Merge to develop for prod deplyment

---

api/barriers/serializers.py

Allowing frontend to push status summary, when the report was already resolved.

allowing frontend to push report status summary

---

.circleci/config.yml
api/interactions/serializers.py

The API currently only returns document `status` which = `virus_scanned` whether it passed or not. We also need to return `av_clean` which states whether the document passed or failed the av check.

MAR-217: Return 'av_clean' and 'av_reason' fields for uploaded documents

---

Procfile
api/barriers/csv.py
api/barriers/serializers.py
api/barriers/views.py
api/metadata/utils.py
requirements.txt

* Switch from waitress to gunicorn to keep in line with the frontend. This also allows us to set `timeout`.
* More efficient country, admin area and sector lookups. We no longer have to loop through every country, sector etc for each row.
* More efficient database queries using `selected_related` and `prefetch_related`
* CSV `DictWriter` class is slow - use `extrasaction` parameter to speed it up

MAR-342: Stop csv getting truncated

---

api/user/models.py

Updating an existing saved search is currently causing `maximum recursion depth exceeded`
Make sure not to commit to db when calling `mark_as_notified` within the save method

Ensure mark_as_notified doesn't cause recursion error

---

api/assessment/models.py
api/barriers/mixins.py
api/barriers/models.py
api/collaboration/models.py
api/collaboration/views.py
api/core/models.py
api/interactions/models.py
api/user/models.py
tests/barriers/test_history.py
tests/barriers/test_modified_by.py
tests/saved_searches/test_models.py

* Ensure changes made to barrier-related models (`Assessment`, `Interaction`, `TeamMember`) update the `modified_on` and `modified_by` fields for the `Barrier`.
* To work out what is `updated` and `new` for a saved search, query the barrier `modified_on` and `modified_by` instead of querying the history of the barrier and related models.

MAR-403: Optimise dashboard

---

api/collaboration/serializers.py
api/user/serializers.py
api/user/views.py

* UserList was limited to 400 results - increase this so we can fetch all users
* Split `UserSerializer` into `UserDetailSerializer` and `UserListSerializer` so we can return less data when fetching the user list

MAR-444: Increase user results limit

---

api/history/factories/base.py
api/history/items/barriers.py
api/history/items/base.py
api/history/items/team_members.py
api/history/utils.py

* Ensure history items return the correct empty values instead of always using `None`
* Fixes: https://sentry.ci.uktrade.digital/dit/market-access-pyfe/issues/28849/

MAR-528: Fix history empty values

---

api/barriers/filters.py
api/metadata/constants.py
tests/barriers/test_list_barriers.py

* If the location filter includes a region, include all barriers with a trading bloc associated to that region

MAR-592: Update region filter to return barriers with matching trading blocs

---

docker/local/entrypoint.sh

When running market-access-api locally the web container failed to load as the installed python version in the container seems to be a version ahead compared to the local entrypoint.sh
I've updated the binary pointed to from specific python3.6 to generic python, which always point to the correct version

bump python version to version installed in Dockerfile

---

api/barriers/management/commands/ugly_hack_fixing_modified_on_field.py
api/barriers/migrations/0099_populate_commercial_value.py
api/barriers/migrations/0123_auto_20220401_1346.py
tests/barriers/test_ugly_hack_fixing_modified_on_field.py

This adds a management command to patch the `modified_on` fields of `Barrier` objects that were inadvertently modified by previous migrations. It uses a management command rather than a migration as fixes for previous migrations have been included just in case, and frankly this is a pretty loathsome hack that shouldn't be applied automatically, but run manually in the full and awful knowledge of just how dreadful it is 😉

TSS-203 Fix for Barrier `modified_on` values

---

api/barriers/serializers/data_workspace.py
tests/barriers/test_csv_export.py
tests/barriers/test_datawarehouse.py

This adds the latest progress update to the DataFlow API endpoint, so that DF can consume it and stick it in Data Workspace (though it only uses the status field for now). There is a corresponding PR over on DF which I'll leave in draft until this is released.

TSS-217 DMAS delivery confidence values missing from csv download

---

api/barriers/serializers/data_workspace.py
api/barriers/views.py
tests/barriers/test_datawarehouse.py

The problem arose from a failure to serialise the `User` instance fields in the `BarrierProgressUpdate correctly. This PR beefs up the serialiser to do it correctly.

TSS-221: DMAS data flow receiving 500 error when fetching data

---

api/history/items/delivery_confidence.py
tests/barriers/test_history.py

Delivery confidence history items currently only display the status change. This PR also returns the description a user put for the progress update.

TSS-797: Delivery Confidence Summary in history item

---

api/history/items/action_plans.py
tests/barriers/test_history.py

Sometimes an ActionPlan may not have a user associated with it under assigned_to, if not, then we use the backup_user instead.
https://sentry.ci.uktrade.digital/organizations/dit/issues/103087/?environment=production&project=121&referrer=alert_email

Fix - TSS-1357 - Missing Action Plan Assigned to Sentry error

---

api/barriers/models.py
api/barriers/serializers/barriers.py
api/barriers/views.py

getting rid of Barrier objects method as unnecessary, return a DataFrame not a queryset.
Similarity score now - as part of this dataframe - gets passed to the serializer for response.
Removed caching as we want to test quickly and will be fixed as part of a different ticket

Feature - TSS-1331 - Display related barriers similarity score

---

api/barriers/serializers/public_barriers.py

`barrier.unpublished_changes` property was initially returning a boolean, but has been changed to return a list. The public barrier serializer returns the raw value, so any process previously expecting a boolean would now receive a list instead (Dataworkspace). This change casts the list to boolean

hotfix: Public Barrier unpublished changes type

---

api/barriers/models.py
api/metadata/constants.py
api/related_barriers/manager.py
tests/barrier_downloads/test_views.py
tests/barriers/test_list_barriers.py
tests/metadata/test_metadata.py
tests/user/test_views.py

* Changes to allow for sorting search result by relevancy
* Match metadata to frontend
* Update test to reflect search term name change
* unit test fixes
* Adding barrier code to the corpus for comparing related text searches
* Fixing unit test that was failing on certain dates
---------

Changes to allow for sorting search result by relevancy (#907)

---

api/barriers/models.py
api/barriers/signals/handlers.py
api/related_barriers/management/commands/related_barriers.py
api/related_barriers/manager.py
api/related_barriers/tasks.py
api/related_barriers/urls.py
api/related_barriers/views.py
config/settings/base.py
tests/barriers/signals/test_handlers.py
tests/related_barriers/test_baseline_performance.py

- Baseline tests against https://www.sbert.net/docs/sentence_transformer/pretrained_models.html
- Daily schedule to reindex
- Management command

tss-2129: Related Barriers baseline tests and re-index cron
