.gitignore, api/ping/services.py, api/ping/test/test_ping_view.py, api/ping/views.py, config/urls.py
=> adding pingdom

api/barriers/views.py, api/core/auth.py, api/metadata/views.py
so that they are accessible without user token
=> adding debug capability to views

api/metadata/constants.py, api/metadata/views.py, api/reports/views.py, config/urls.py
Adding Barrier Status metadata for frontend to show barrier details
=> Barrier status metadata

api/barriers/serializers.py, api/barriers/views.py
Fixing resolve status_date parsing bug
=> Barrier resolve bug fix

api/metadata/views.py
barrier_type_categories, 
barrier_chance_of_success, 
barrier_interaction_types
=> exposing barrier metadata 

api/metadata/admin.py, config/settings.py, config/urls.py
Adding admin for maintaining BarrierType model in metadata. Nothing else will be exposed for admin.
=> adding admin module

api/metadata/views.py, config/settings.py
New setting for enable/disable hawk
=> Hawk settings fix

api/barriers/models.py, api/barriers/serializers.py, api/barriers/views.py, api/metadata/constants.py, config/urls.py, requirements.txt
Open API to change status of barriers that were marked as Resolved/Hibernated.
Lint/format refactoring
=> Barrier resolve api

api/barriers/serializers.py, api/reports/views.py, requirements.txt
Fixed:
Hawk requirements
user object in child models
=> Merge issues

api/reports/views.py
fixing corner case where reporting process
=> fixing corner case where reporting process

requirements.txt
=> upgrade django 2.1.2

.circleci/config.yml, .gitignore
=> adding circleci

api/barriers/serializers.py, api/barriers/tests/test_status_history.py, api/barriers/views.py, config/settings/local.py
incorrect DEBUG setting has caused request.user to be ignored. Which is now fixed both in settings and code.
=> Report created by fix

api/metadata/constants.py, api/metadata/tests/test_metadata.py
To change content to match ticket
=> Update constants for status type

api/barriers/tests/test_barrier_details.py, api/barriers/views.py
where barrier_type or priority is made null, when editing other barrier fields.
=> fixing barrier update bug

config/settings/base.py
increase barrier page size to 200 before deciding on what to do with it
=> increase page size

config/settings/base.py
adding missing slack setting regressed by master merge
=> adding missing slack setting regressed by master merge

api/barriers/management/commands/barrier_stats.py
fixing stats django command to show more info
=> fixing stats to show more info

api/barriers/tests/test_list_barriers.py, api/barriers/views.py
fixing count API, to have more flexibility for FE to show numbers based on filters it has applied.
=> Counts hot fix

api/barriers/views.py, api/metadata/models.py
enable and fix full_history API so as to serve ad-hoc requests from team members and others.
=> enabling full_history api for ad-hoc requests

api/interactions/tests/test_interactions.py, api/interactions/views.py
changing the way document removal is handled, when it was attached to a note
=> changing the way document removal is handled

config/settings/base.py
changing page size temporarily
=> changing page size temporarily

api/barriers/views.py
fixing status history after new status changes
=> fixing status history after new status changes

api/dataset/serializers.py, config/settings/base.py
* Fix broken serializer fields
* Add Hawk credentials for data workspace
=> MAR-228: Data workspace endpoint

api/user/migrations/0008_populate_user_emails.py, api/user/views.py
- default email to 'email' field in sso details in case 'contact_email' is not present
=> MAR-145 - improve get-user flow 

api/barriers/history/assessments.py, api/barriers/history/barriers.py, api/barriers/history/base.py, api/barriers/history/notes.py, api/barriers/history/team_members.py, api/barriers/history/wto.py
* Keep previous history items in initial query so we have something to compare subsequent items against
* Filter these older history items out afterwards in python
=> Move history start_date filtering to base class

api/barriers/views.py, tests/barriers/test_list_barriers.py
* Ensure WTO search filters OR together instead of AND
=> MAR-343: WTO 'or' filters

config/settings/base.py, config/settings/dev.py, config/settings/production.py, config/settings/uat.py, poetry.lock, pyproject.toml, requirements.txt
Use `django_log_formatter_ecs` to add correlation ids to logs
=> MAR-247: Add correlation ids to logging

Procfile, api/documents/av_scan.py, poetry.lock, pyproject.toml, requirements.txt
* Upgrade celery
* Use eventlet instead of gevent
=> MAR-427: Fix file uploads

api/barriers/history/__init__.py, api/barriers/history/barriers.py, api/barriers/history/public_barrier_notes.py, api/barriers/history/public_barriers.py, api/barriers/models.py, api/barriers/views.py, tests/barriers/test_history.py
Add history for:
* Public Barrier Notes
* All sectors field of PublicBarrier
* Public barrier country
=> MAR-213: Extra history

api/barriers/management/commands/publish_barriers_from_csv.py, api/barriers/public_data.py, config/static/sector.json, tests/dataset/test_views.py
* Management command to publish public barriers from a csv file
* Update sectors.json so that local sectors matches dev
=> MAR-698: Publish barriers from csv file

api/barriers/serializers/csv.py, api/barriers/views.py
Filter for government organisations in python during csv download
=> MAR-720: Speed up csv download

api/user/models.py, tests/saved_searches/test_models.py
MAR-763 notifications on by default.
=> MAR-763: Make notifications the default for searches

api/barriers/models.py
MAR-1030 - Adding filter for ignore barriers with 'all sectors'
=> MAR-1030 - Adding filter for ignore barriers with 'all sectors'

.pre-commit-config.yaml, api/barriers/tasks.py, docker/local/Dockerfile
May fix the CSV download problem of Excel failing to detect the file's UTF-8 encoding.
Also: fix the Dockerfile, and update pre-commit.
=> TSS-177 UTF-8 characters in downloads

api/barriers/serializers/csv.py, api/barriers/serializers/data_workspace.py, api/barriers/views.py, tests/barriers/test_csv_export.py, tests/barriers/test_datawarehouse.py
And CSV as well while we're about it 🙂
=> TSS-491: Add resolved pb100 status to data workspace

.gitignore, api/barriers/serializers/barriers.py
Adding export_description to BarrierDetailSerializer
Added local.env to .gitignore
=> Feature - TSS-770 - Change affected goods edit page

api/barriers/fields.py, api/barriers/serializers/barriers.py, api/barriers/serializers/base.py
Add main_sector to Barrier detail serializer for use in frontend display/updates
=> TSS 773 sector edit page

.circleci/config.yml
added codecov.io to cirlci config.yml
=> Feature - TSS-866 - Codecov integration

Makefile, config/static/country.json
Changed country metadata in API mock metadata, not just python-frontend.
related and nearly identical to uktrade/market-access-python-frontend#480
=> Fix - TSS-532 - Reunion name change

api/barriers/serializers/data_workspace.py
Use default of None if first, last name not found
=> Fix default values for First Name, Last Name where do not exist

api/barriers/serializers/data_workspace.py
added tags to data workspace barrier serializer.
=> Task - TSS-914 - Expose barrier tags to data workspace

config/settings/base.py
=> Hotfix - TSS-919 - Reinstating documents bucket

api/barriers/serializers/barriers.py, api/barriers/views.py, api/metadata/constants.py, tests/barriers/test_list_barriers.py
Reverts uktrade/market-access-api#566
=> Revert "Fix - TSS-931 - Duplicates in search results"

api/barriers/models.py
changed start_date on the BarrierFIlterSet to use a normal filter rather than in, we can do the splitting in the filter itself
=> Fix - TSS-920 - Search form refactor

.circleci/config.yml, README.md, api/barriers/models.py, poetry.lock, pyproject.toml
* splitting up tests
* setting paralllelism to 4
* fixing codecov issues
* using parallel package
* no combining
* parallelising and combining coverage files
* removing combining thing
* using coverage to run pytest in parallel
* removing --cov arguments to pytest so coverage takes it all
* specifying which folder to get coverage for
* removing old config.yml stuff
* updating README.md
=> RC 42 Years Young

.circleci/config.yml, README.md, api/dataset/views.py, api/healthcheck/views.py, api/metadata/views.py, api/user/views.py, config/settings/base.py, config/settings/test.py
HAWK is always enabled, removed Data Workspace HAWK stuff as it's not used
=> Feature - TSS-1055 - Call API for metadata

.circleci/config.yml, docker/local/Dockerfile, poetry.lock, pyproject.toml, requirements.txt
upgrading poetry pin. This will help us to use the generated dependabot security updates.
=> Fix - Unpinning CircleCI Poetry Version

.circleci/config.yml, api/dataset/views.py, api/healthcheck/views.py, api/metadata/views.py, api/user/views.py, config/settings/base.py, config/settings/test.py
Reverts uktrade/market-access-api#628
=> Revert "reverting metadata changes"

api/metadata/utils.py
Demanding that the DH returns a response and raising an exception if it doesn't for metadata
=> Feature - TSS-1055 - Demand DataHub response

api/barriers/serializers/data_workspace.py, tests/dataset/test_views.py
Main Sector” should show “all sectors” IF, “main sector” is null AND "All Sectors” is TRUE.
Added tests
=> Feature - TSS-1081 - DW Pipeline main_sector change

api/barriers/serializers/data_workspace.py, tests/barriers/test_datawarehouse.py
* adding pb100 to priority level
* changed priority level to a method field
=> Release - Man Uka of Lord - a

.github/dependabot.yml, .github/workflows/recreate-poetry-requirements.yml
requirements.txt file is regenerated everytime pyproject.toml or poetry.lock is modified
=> Feature - TSS-1112 - Aligning dependabot resolution

api/core/middleware/policy_headers.py, config/settings/base.py
Added cache control and cross domain policy to response headers
=> Response Security Headers

.github/dependabot.yml
only allowing security updates
=> Fix - Only allowing dependabot security updates

api/history/v2/enrichment.py
PublicBarrierLocation should only return a single string, and not a dict of values
=> Fix - TSS-1398 - Fixing public barrier location history

api/barriers/serializers/data_workspace.py, api/metadata/utils.py, tests/barriers/test_datawarehouse.py, tests/dataset/test_views.py
format
format
date_barrier_prioritised field
Rename top_priority_date > top_priority_requested_date
format
fix test
format
=> tss-1693: Barrier scoping tag date

api/dashboard/service.py, api/dashboard/views.py, tests/dashboard/test_queries.py
- Move logic into own module to slim down the view
- unit test all the calculations of the user barrier counts
TODO: fix financial year?
=> tss-2187: Testing of dashboard counts
